export { IoIosStar, IoIosArrowDown } from 'react-icons/io'
export { HiOutlineCurrencyDollar } from 'react-icons/hi2'
export { IoCarSportOutline, IoLogoWhatsapp } from 'react-icons/io5'
export { TbPlaneDeparture } from 'react-icons/tb'
export { PiHouseLineBold } from 'react-icons/pi'
export { MdEmail, MdOutlineSecurity } from 'react-icons/md'
export { LuBadgePercent } from 'react-icons/lu'
export { FiUsers } from 'react-icons/fi'
export { FaRegMoneyBillAlt } from 'react-icons/fa'
